### ISSUE TITLE
semop() error

### ISSUE THREAD

**Issue by aldem** [phaag/nfdump#100]
Hi,

When collecting IPv4/IPv6 traffic (NetFlow v9, source is ipt_netfilter 2.2), I see messages like:

semop() error in bookkeeper.c line 108: Invalid argument
semop() error in bookkeeper.c line 123: Invalid argument

which start to appear after approximately 1 day of continuous collection. The collected traffic is very low (this is a test system), around 200-300 flows every 5 minutes.

On another system, where traffic is significantly higher (200000-300000 flows every 5 minutes), but only IPv4, I see no such messages (though I am not sure that IP version has something to do with this).

nfdump version is 1.6.16, compiled & run on debian stretch (with all current updates).

Is this an real issue or it could be safely ignored? If this is an issue, what could be done to solve it?

Thank you!

**Comment by phaag** [comment]
It puzzles me a bit, if you report, that it appears after approx. one day. 
The purpose of this semaphor is to synchronise with nfexpire or option -e to nfcapd in order to calculate correctly the accumulated flow data file size. The traffic rate is not relevant for this functionality. 
As it happens on one system only I assume it could be a system issue - maybe kernel related as semphores are a system/kernel API. 
Check you system semaphores with the command ipcs, if you see some strange behaviour.

I guess this issue will go away after a reboot.

If you do not auto expire with nfexpire or option -e to nfcapd, the error message can be ignored. Otherwise you potentially risk a faulty behaviour when expiring data.

**Comment by aldem** [comment]
ipcs shows nothing suspiciuos (one shared segment and one array, both exists only when nfcapd is running. and they still exist when issue appears), two systems are running the same distro & kernel (4.9), though one is physical (it processes IPv4 traffic), and another is in KVM (processes IPv6 mostly). KVM should not cause such problem, though, as IP version - but everything else is identical.

Reboot does not really helps - issue disappears for a while even when I restart nfcapd, then reappears again.

**Comment by phaag** [comment]
This is really strange. I do not get the point why it does throw this error after running fine for a day or so. IPv4 or v6 does not matter either. Semaphores are pure kernel issues. The relevant code in bookkeeper run fine for years so I really have not clue.
I will try to craft a debugging version of bookkeeper and send it to you.

**Comment by aldem** [comment]
I hope you did not invest too much time into debugging version, as I have found the reason.

When nfcapd is run as user nobody,
and when something else is switching to nobody (cronjob in particular, using su),
and when all this is managed by systemd+logind,
and when that logind has "RemoveIPC=yes" configured (the default),
then it fails, as logind removes all semaphores (but not shm) which belong to user nobody once cronjob is finished (on session cleanup).

So, indeed, you were right - the problem is outside and is not related to nfcapd at all, but it was really difficult to nail it.

The only thing I do not understand is how could I miss (first time) that semaphore array is not there - I am quite sure that I have seen it..

**Comment by phaag** [comment]
Good to hear, that the problem is solved!  :) 
So I close the ticket.
