### ISSUE TITLE
Json output format

### ISSUE THREAD

**Issue by ghramos** [phaag/nfdump#113]
Hello.

I'm writing in reference to JSON output format. I'm using nfdump 1.6.17 and JSON output format does't works. CSV works, but JSON not.

I'm using these commands:
nfdump -R /data/nfcap/ASA/ -s ip/flows -o json > output.json 
nfdump -R /data/nfcap/ASA/ -s ip/flows -o csv > output.csv

What am I doing wrong?

Thank you @phaag 
[output.zip](https://github.com/phaag/nfdump/files/1990010/output.zip)

**Comment by ghramos** [comment]
@phaag The command "nfdump -r /data/nfcap/ASA/archive -I -o csv" does't work too.

**Comment by phaag** [comment]
The json output format works for flow listings or record statistics but not for element statistics.
./nfdump -r <file> -o json
./nfdump -r <file> -s record -o json
Both work

./nfdump -r <file> -s ip -o json
does not work as this is no record output. -o works for record outputs.

Furthermore tranalyzer is a different type of tool and not comparable!

**Comment by stbf104g** [comment]
look at new version, we log into your tool now
--------------------------------------------
On Sun, 6/24/18, Peter Haag <notifications@github.com> wrote:

 Subject: Re: [phaag/nfdump] Json output format (#113)
 To: "phaag/nfdump" <nfdump@noreply.github.com>
 Cc: "stbf104g" <stefan_burschka@yahoo.com>, "Comment" <comment@noreply.github.com>
 Date: Sunday, June 24, 2018, 12:54 PM
 
 The json output format works for
 flow listings or record statistics but not for element
 statistics.
 
 ./nfdump -r  -o json
 
 ./nfdump -r  -s record -o json
 
 Both work
 ./nfdump -r  -s ip -o json
 
 does not work as this is no record output. -o works for
 record outputs.
 Furthermore tranalyzer is a different type of tool and
 not comparable!
 
 —
 You are receiving this because you commented.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
