### ISSUE TITLE
TCPFlags sometimes in hex

### ISSUE THREAD

**Issue by simPod** [phaag/nfdump#132]
When reading flow files with nfdump, sometimes the TCP Flags output is `.A....` and similar as specified in docs but sometimes it's in hex like `0x52` or `0xc2`.

What does it mean and why is it so?

Calling with `nfdump -o "fmt:%flg" -N -6 -r "filepath"`

**Comment by simPod** [comment]
It is value from this table

```bit    flag
value  name  description
------+-----+-------------------------------------
0x8000       Zero (see tcpHeaderLength)
0x4000       Zero (see tcpHeaderLength)
0x2000       Zero (see tcpHeaderLength)
0x1000       Zero (see tcpHeaderLength)
0x0800       Future Use
0x0400       Future Use
0x0200       Future Use
0x0100   NS  ECN Nonce Sum
0x0080  CWR  Congestion Window Reduced
0x0040  ECE  ECN Echo
0x0020  URG  Urgent Pointer field significant
0x0010  ACK  Acknowledgment field significant
0x0008  PSH  Push Function
0x0004  RST  Reset the connection
0x0002  SYN  Synchronize sequence numbers
0x0001  FIN  No more data from sender```

But wondering why is it inconsistent then? 🤔

**Comment by phaag** [comment]
nfdump handled the bitwise TCP flags 0x01 (FIN) to 0x20 (URG) as readable strings. Anything outside ( > 0x63 ) was not defined and printed as hex value in order to display this fact. I added now "ECN Echo" and CWR "Congestion Window reduced". Looks like many kernels started to use ECN Echo, which resulted in a printed hex value. With the two added flags, you always will have a strings value. 
Please note, most flows export only 8 bits for TCP flags.
Thx for reporting this issue
