### ISSUE TITLE
[Feature Suggestion] nfdump should read dump files in one go (with big block size) and analyse them in memory afterwards

### ISSUE THREAD

**Issue by xtaran** [phaag/nfdump#155]
Even if the block device and file system of `nfcapd`'s storage directories is capable of 2 GB/s reading throughput, `nfdump` seems to only be able to analyse about 85 MB/s (on a specific hardware).

Since read throughput on devices like NVMe seems to decrease a lot when data is read with rather small block sizes (especially < 1kB), and `nfdump` seems to read `nfcapd`'s dump files in rather small per-flow chunks (or similarly small chunks), I assume that reading a `nfcapd` dump file in one go and then analysing it in memory would speed up `nfdump`'s execution quite a bit, given enough memory and a adequately fast CPU. (Memory shouldn't be a big issue on file sizes between e.g. 50 and 500 MB.)

With the same `nfcapd` data and the same `nfdump` filter request, I observed reproducibly `nfdump` 1.6.17 execution time differences between block devices with different reading speed (NVMe vs SSD RAID1). I especially saw slightly lower execution speeds on the NVMe block device compared to the SSD RAID1 despite the SSD RAID1 is distinctively slower (factor 2.2) than the NVMe at block sizes of 1 MB or higher.

I was able to reproduce the latter behaviour (NVMe slightly slower than SSD RAID1) by just reading the same files as `nfdump` into `/dev/null` with `dd bs=105`, i.e. the same low reading block size on both devices. (105 bytes block size was the value which gave me about the same `dd` execution speed as `nfdump`.)

For me this proves that `nfdump`'s execution speed is not only a result of the CPU speed but also a result of the block size at which it reads the dump files. It though is probably not the primary bottle neck as bash's timing summary for about 22 GB of `nfcapd` files (each file being around 70 MB of size) shows: 

`nfdump  'port 22'` on 22 GB of data on NVMe:
```
real    4m26.837s
user    3m21.507s
sys     0m48.196s
```

`nfdump  'port 22'` on 22 GB of data on SSD RAID1:
```
real    4m3.241s
user    3m15.479s
sys     0m46.882s
```

Comparing the timing data with pure `dd` on the NVMe:

```
$ time for i in * ; do dd bs=512 if=$i of=/dev/null; done
real    1m0.695s
user    0m18.692s
sys     0m41.544s
$ time for i in * ; do dd bs=4M if=$i of=/dev/null; done
real    0m17.596s
user    0m0.158s
sys     0m9.285s
```

Please note that while the `sys` time in the first `dd` example was about the same as the `nfdump` examples above (between 40 sec and 50 sec) while the bigger block size massively improved that value down to about 9 sec. So my expectation is that we will also gain these 30 sec to 35 sec of speedup with `nfdump` (maybe even more) if it would read each file in one go instead of flow by flow. Given the time `nfdump` needed for everything, I would expect a speedup of approximately 15% in the above case.

(JFTR: I did a `echo 1 > /proc/sys/vm/drop_caches` at the start of each test so that the caches won't play tricks on me and my measurements.)

Hence I suggest to add an option to `nfdump` which reads every `nfcapd` dump file in one go into memory, analyses it there, and then reads the next whole file into memory. (Or maybe even read the next file while still analysing the previous file, but that additionally needs some concurrency management.)

**Comment by phaag** [comment]
Please be careful when doing performance tests, as a lot of side effects may come into play.
The bottle neck is not the reading or block size. Most time is spent to convert binary to ascii.
To test speed, one option would be:
nfdump -r <file> -w /dev/null
It does no ascii conversion and simply reads flows in binary form to the output - /dev/null

Furthermore, a big impact has the compression. My recommendation is to use -z for nfcapd, in order to compress flows. This also speeds up processing flows. nfdump.

Filteriing data has a minor impact on execution speed and depends heavily on the form of your filter. 
Wether using 'port 22' or no filter at all has almost no practical impact. 

nfdump uses internally a buffer size of 1MB block size. In the past, it turned out to be a good value to read/process flows. Reading all data in one go does not necessarily speed up the overall time, but uses substantially more memory.

There is a known performance issue with nfdump: It is still single threaded. However, multiple threads would not always reduce overall execution time. It may speed up in normal read -> filter -> output process. As soon as you have some statistics this could lead again to some impact.

I am currently in progress to add threads to all nfdump tools, but it needs a major change of the code.

**Comment by phaag** [comment]
For now I will close this issue. Feel free to reopen, if you want to discuss more on this topic.

**Comment by xtaran** [comment]
That's fine. During our discussion and my tests I realized that we're already using compression, i.e. all numbers above are _with_ compression and hence my reasoning above is bogus anyways.
