### ISSUE TITLE
Cannot specify output format (-o) when generating stastics (-s)

### ISSUE THREAD

**Issue by bruceg** [phaag/nfdump#183]
When using the `-s` option to generate a statistic table, the output format option `-o` is ignored, except for the IPv6 flag (with either the `-6` or `-o line6` etc options). It would be useful to be able to use custom formats (`-o fmt:`) with those tables as well, particularly to drop uninteresting columns.

**Comment by phaag** [comment]
This is partially true. -s <element> for example -s ip always returns in a fixed format - yes. On the other side -s record returns a record statistics, which follows fmt rules. 
The fmt definition will be added in a future release. Meanwhile you work around by creating a record statistics and force aggregation on an IP
Instead of -s srcip/bytes
try -s record/bytes -A srcip -o "fmt: ..."

**Comment by bruceg** [comment]
That helps, thanks.
