### ISSUE TITLE
-B option doesn't consider the reporting router

### ISSUE THREAD

**Issue by pullwoods** [phaag/nfdump#268]
Hello all, I consider -B option very useful but unfortunately it aggregates the flows without considering the reporting router.
Therefore the flows crossing more routers are aggregated into a single record associated to the first reporting router.
Is there a way to aggregate bidirectionally the flows but keeping one record for each router?
Thanks a lot

**Comment by phaag** [comment]
Currently the router is not considered, as the flow is defined independently from the router. If the router is integrated, you would be required also to print the router IP addr (or exporter ID alternatively) otherwise the result is ambiguous. The question is - is this a corner case or a user demand.
