### ISSUE TITLE
nfexpire causes infinite loop, fills up logs

### ISSUE THREAD

**Issue by jeremytouve** [phaag/nfdump#271]
I have created a fairly simple nfsen setup with about 8 sources.
If I enable a time based expiration on the default live profile, nfexpire gets caught in a loop and fills /var/log/debug and /var/log/syslog with the following message:
```
Jan 28 22:47:07 localhost nfsen[1114923]: nfexpire: 
Jan 28 22:47:07 localhost nfsen[1114923]: nfexpire: unlink() error in expire.c line 681: No such file or directory
```
This ends up breaking my setup completely (although that is more of a nfsen issue).

**Comment by phaag** [comment]
Fixed the endless loop in expire.c in case of files not found.
For some reason, another process than nfexpire deletes files, which results in data inconsistency. You have to rebuild those profiles in order to resync with nfexpire, otherwise nfexpire always gets wrong information. Use ./nfsen -r <profile>
