### ISSUE TITLE
Documentation of `nfpcapd` output format

### ISSUE THREAD

**Issue by kdhageman** [phaag/nfdump#275]
I am working with large `pcap` files of raw traffic from which flows are extracted using `nfpcapd` and I am trying to figure out how to analyze these flows afterwards with some custom tooling.

I know `nfdump` is capable of parsing the output of `nfpcapd` and turn it into `csv` files, but I was hoping to read the binary files generated by `nfdump` directly, but I cannot find any documentation about the file structure.

Any suggestion of how to get started?

**Comment by phaag** [comment]
nfcapd as well as nfpcapd generate the same output file format. This is nfdump specific and it's layout can be found in nffile.h. The record format is described in nfx.h. If you want to post process nfdump records, I would recommend the json format (-o json) instead of csv, which is somewhat limited. 
If you want to directly process nfdump files, you may create your own C program, using nfreader.c as an example.
