### ISSUE TITLE
Incorrectly display the amount of traffic received

### ISSUE THREAD

**Issue by hhamed1989** [phaag/nfdump#331]
Hi
I have installed nfdump service o nubuntu 20.04 . But the amount of traffic I am receiving from multiple routers is less than the actual amount. To check amount of traffic was sent, I stopped the nfdump service and installed the ManageEngine NetFlow Analyzer tool. The amount of traffic received and displayed on Manage Engine NetFlow Analyzer is correct and much more than the received traffic on nfdump service. Sample rate settings on both services are equal to 1.
I use this configuration for nfcapd 
"/usr/local/bin/nfcapd -w -D -p 9996 -B 10485760 -t 60 -z -T +12,+13 -I Chavoosh-NetFlow -P /var/run/nfcapd.pid -l /home/data/netflow/live/Chavoosh-NetFlow"
Please help me how to solve the problem.
Thanks

**Comment by phaag** [comment]
The amount of traffic you see in nfdump is the result of the received flows. I am not aware of any bug regarding calculating the amount of traffic. Just with your explanation given above, it's not possible to debug the problem - sorry.
Please be sure to compare on both sides the same values.

**Comment by hhamed1989** [comment]
The amount of traffic Means, Bandwidth based on Gbps. we Test ME Netflow Analayzer and nfdump on the same machine with same traffic forward from routers. but the BW in nfdump is half .
I have some errors on syslog like "Sequence Errors: 18," .I try to increase the bufflen up to 5368709120 but nothing chnged.
I have an server with Intel X5660 24 cores and 64GB Memory with high performance M2 samsung hard drive that ubuntu 20.04 run on it.
could you please help me what is the best value for the bufflen with about 40 Gbps Customer traffic (not netflow traffic) or any kernel setting or option that I used for best performance of nfcapd and nfdump !?
Best Regards,

**Comment by phaag** [comment]
Hmm .. if you only have 18 Sequence errors, then the difference should not be that much. Increasing the buffer infinitely does not fix a permanent lag. You may try to omit -z, if you have fast storage. Otherwise you may try the unicorn branch, which uses multithreading for collecting and storage.  -B 10485760  should work actually fine.
Relevant for the collector is not the customer bandwidth, but the Flows/s. 
How much difference do you see? If you have multiple routers try multiple collectors.
What netflow version are you collecting? v5/v9/ipfix?

**Comment by phaag** [comment]
btw. Sampling - you you verified, bith collectors apply the correct sampling rate?

**Comment by phaag** [comment]
if you have that long duration times, that, this flow carries permanent traffic. 
In order to split this flow into several smaller flows, you should check the active timeout on the router. This timeout should not be larger that the collection period per file. For example, if you rewind files every 300s the active timeout should be not larger that 300 or fractions thereof such as 150, 100, 60, 50, 30, 20, 10s.
The entire flow is then split over multiple files. 
To evaluate the full duration, you need to select multiple files for nfdump.

**Comment by hhamed1989** [comment]
Thanks for your help, I add these lines to Cisco 7500,
mls aging long 64
mls aging normal 32
ip flow-cache timeout active 1
ip flow-cache timeout inactive 15
now I didn't have flow with 2047s duration and changes make better for me. but some flows still between 60 - 85 s .
thinks should changes mls aging long 64, mls aging normal 32 to fix it.
do you have any advice about Cisco 7500 netflow configuration ?
Best Regards,

**Comment by phaag** [comment]
Your flows have most likely always applied a combination of active and inactive timeout. This depends on when a flow switches from active to inactive and back again. It's something you have to figure out what suits you best. Smaller timeouts put more load on the router and collector, larger timeouts result in longer durations, and therefore flow start time outside the current file. You may go either way. The important thing is, that you know your devices  and when they export flows, so you can correctly read and interpret the flows, presented by nfdump.
I am not a CISCO expert, therefore I can not advice you regarding the detailed config. You may find appropriate answers in dedicated CISCO network forums.
