### ISSUE TITLE
Sharding per minute neflow data into multiple files 

### ISSUE THREAD

**Issue by viran87** [phaag/nfdump#343]
@phaag 
We process per minute nfcapd file and generate some insight to support some use-case and features in our product. To achieve this, our process engine has to timely process these files in < 1 minute (per file) so that the lag does not build up. With IPv4 netflow data, we have seen the per minute file size upto 500 MB (~50 M records) which we are able to process in time.

But currently with the IPv6 environment, we have seen netflow data growing upto ~2 GB for ~80 M records.
This has an adverse impact on our process engine and it is taking > 4 minutes to process each file. Though we have identified some optimisations in our processor, it won't be sufficient to bring the processing time to < 1 min per file. 
Hence we're thinking of splitting the incoming data so that it creates multiple files (say 5 files per minute) which can be processed in parallel to bring the time to < 1 minute. 

The splitting should not be a random split, but based on some specific sharding technique. Our use-case requires the same src/dst ip pair to be present in the same file for further processing.
For this we will have to make changes in the existing codebase as this splitting is not present out of the box.
Would like to know your feedback on this. Is this the right approach?

**Comment by phaag** [comment]
Is the processing bottleneck within nfdump or externally in your own processing chain? If it is within nfdump, we certainly can discuss optimisation possibilities.  

If you need the same src/dst ip pair present in the same file, it's not something available out of the box. One option might be to let nfdump create bi-directional flows (-B) and split those files into smaller segments. Otherwise you need to code your own splitter. It could get tricky as you would need to deal with corner cases. As I don't know your detailed requirements it's a bit difficult to tell, if this is the right approach. If your processing works with bi-directional flow records, I would prefer that approach, as this is the easiest one.

Fell free to contact me offlist for more options.
