### ISSUE TITLE
timestamps on IPFIX from IOS-XR 6.0 are not working

### ISSUE THREAD

**Issue by jejenone** [phaag/nfdump#36]
Cisco just released IPFIX support in IOS-XR 6.0. Timestamps don't seem to be working with nfdump.

{code}
jfleury@36netops3:/disk/data/nfdump$ nfdump -r db/edge01.mrs01/2016/09/07/nfcapd.201609072238 -o raw | head -100

Flow Record:
  Flags        =              0x86 FLOW, Sampled
  export sysid =                 2
  size         =                92
  first        =                 0 [1970-01-01 00:00:00]
  last         =                 0 [1970-01-01 00:00:00]
  msec_first   =                 0
  msec_last    =                 0
  src addr     =    80.249.164.124
  dst addr     =     162.158.21.12
  src port     =                80
  dst port     =             52241
  fwd status   =                 0
  tcp flags    =              0x00 ......
  proto        =                 6 TCP
  (src)tos     =                 0
  (in)packets  =             49152
  (in)bytes    =          28311552
  input        =               133
  output       =                 8
  src as       =              5483
  dst as       =                 0
  src mask     =                24 80.249.164.0/24
  dst mask     =                32 162.158.21.12/32
  dst tos      =                 0
  direction    =                 0
  bgp next hop =           0.0.0.0
  ip router    =      162.158.20.1
  received at  =     1473287928060 [2016-09-07 22:38:48.060]
{code}

This renders nfdump command unusable. 

{code}
jfleury@36netops3:/disk/data/nfdump$ nfdump -I  -t-600 -M db/edge01.mrs01 -R .  -s record/bytes
Ident: edge01.mrs01
Flows: 44438237
Flows_tcp: 44171585
Flows_udp: 252007
Flows_icmp: 13668
Flows_other: 977
Packets: 775532773376
Packets_tcp: 770959589376
Packets_udp: 4306845696
Packets_icmp: 250331136
Packets_other: 16007168
Bytes: 582753486061568
Bytes_tcp: 581400941953024
Bytes_udp: 1251934371840
Bytes_icmp: 98734702592
Bytes_other: 1875034112
First: 1472687706
Last: 1473326628
msec_first: 268
msec_last: 0
Sequence failures: 580596

jfleury@36netops3:/disk/data/nfdump$ nfdump  -t-600 -M db/edge01.mrs01 -R .  -s record/bytes
Aggregated flows 0
Top 10 flows ordered by bytes:
Date first seen          Duration Proto      Src IP Addr:Port          Dst IP Addr:Port   Packets    Bytes Flows
Summary: total flows: 0, total bytes: 0, total packets: 0, avg bps: 0, avg pps: 0, avg bpp: 0
Time window: 2016-09-08 09:08:48 - 2016-09-08 09:23:48
Total flows processed: 102367, Blocks skipped: 0, Bytes read: 9418196
Sys: 0.021s flows/second: 4831822.9  Wall: 0.015s flows/second: 6666688.4
{code}

Attaching pcap extract. Wireshark seems to have no problem reading the timestamps.

[mrs_ipfix_2.pcap.zip](https://github.com/phaag/nfdump/files/461260/mrs_ipfix_2.pcap.zip)

{code}
jfleury@36netops3:/disk/data/nfdump$ nfdump -V
nfdump: Version: 1.6.15
{code}

tested with 1.6.13 too, same issue.

**Comment by phaag** [comment]
Thx. I fix it.

**Comment by jejenone** [comment]
Hi @phaag - Do you mean you have fixed it, or are you going to fix it ?

**Comment by phaag** [comment]
After looking into the pcap, I can tell, that this is not an nfcapd issue, but a CISCO issue.

What is it all about:
The data exported is IPFIX. IPFIX has a lot of elements. I can refer to the IANA site http://www.iana.org/assignments/ipfix/ipfix.xhtml

Many of these elements are identical to netflow v9, but it has a lot of additions.
Many IPFIX exporters export the timestamps with the elements 152, 153:

**152	flowStartMilliseconds**
_dateTimeMilliseconds The absolute timestamp of the first packet of this Flow. milliseconds_
**153	flowEndMilliseconds**
_dateTimeMilliseconds	The absolute timestamp of the last packet of this Flow. milliseconds_

In your stream of the  IOS-XR 6.0, the start and end timestamps are announced with the elements 21, 22. 21 and 22 are the default elements in many v9 exporters. The difference to 152, 153 is, that 21,22 are relative time stamps - relative to the boot time of the device. In v9 the boot time is announced by the exporter in the header of a data record for all flows in that record. IPFIX has different header data structures and no sysup time in the header.

The IPFIX RFC says:
**21	flowEndSysUpTime**	unsigned32
_The relative timestamp of the last packet of this Flow. It indicates the number of milliseconds since the last (re-)initialization of the IPFIX Device (sysUpTime). sysUpTime can be calculated from systemInitTimeMilliseconds._

**22	flowStartSysUpTime**	unsigned32
_The relative timestamp of the first packet of this Flow. It indicates the number of milliseconds since the last (re-)initialization of the IPFIX Device (sysUpTime). sysUpTime can be calculated from systemInitTimeMilliseconds._

For both elements: _sysUpTime can be calculated from systemInitTimeMilliseconds_
systemInitTimeMilliseconds is element 160:

**160	systemInitTimeMilliseconds	dateTimeMilliseconds**
The absolute timestamp of the last (re-)initialization of the IPFIX Device.

However, none of the templates in your pcap contains the element 160. Therefore, it is not possible to calculate the timestamps for start and end of the flow.

In order to fix that, CISCO needs to fix their templates to add either element 160, or switch to elements 152, 153 which is most common for many IPFIX exporters. 
Up to now, nfcapd does not decode element 160, so if CISCO decides to go that way, please let me know, then I can add that. If they switch to 152, 153 it works out of the box.

**Comment by jejenone** [comment]
Thank you, that is very valuable information that I'll send along to Cisco.

**Comment by phaag** [comment]
Not an nfdump issue.
