### ISSUE TITLE
Compression test ./nftest

### ISSUE THREAD

**Issue by ekbfh** [phaag/nfdump#40]
I can't find where i can find 'nftest' binary.

Even if i have configured with './configure --enable-nfprofile --enable-nftrack --enable-devel'
This string is from the manual:
_You can check the compression speed for your system by doing ./nftest ._

**Comment by phaag** [comment]
just do:
make nftest

**Comment by ekbfh** [comment]
It's not working. 
There is no rule for 'nftest'

**Comment by phaag** [comment]
Sure it does. I use it.

**Comment by ekbfh** [comment]
Dear Peter, please have a look:
My steps:

autoreconf -if'
./configure
./make nftest 
"No rule to make target ''.  Stop./// Нет правила для сборки цели «nftest».  Останов."

I think, that rule about nftest there is only in bin/Makefile, not in the root folder. (i used grep -R nftest.c *)

**Main question**: why it is forbidden to use **-j instead of -z** in nfsen? I simply can't find a proper value in the config file.

**Comment by phaag** [comment]
Hi,
nftest is build on the targed 'check' - 'make check' builds nftest.

To your question: It is not forbidden to use -j instead of -z. If your servers
are powerful enough, use -j. It is not recommended, as compression with -j
uses much more CPU and take much longer than -z. This puts a risk to loose flows
on a busy network.

Hope, this helps

	- Peter
