### ISSUE TITLE
pps/bps avg 0 when flow is 1

### ISSUE THREAD

**Issue by thezoggy** [phaag/nfdump#413]
I've noticed that the avg for pps/bps is 0 if there is only 1 flow, but bpp does show a value.
This was also seen in nfdump 1.6.x. Just wanted to note it in our records if this is expected or just an oversight.

example:
```
src host 2a03:28...c:0:38d9
Top 10 Dst IP Addr ordered by flows:
Date first seen                 Duration Proto       Dst IP Addr    Flows(%)     Packets(%)       Bytes(%)         pps      bps   bpp
2023-02-14 17:17:27.712     00:00:00.000 any    2800:81..2:33::4        1(33.3)    10000(33.3)   800000(33.3)        0        0    80
2023-02-14 17:18:29.618     00:00:00.000 any    2804:d8..ac:6::c        1(33.3)    10000(33.3)   800000(33.3)        0        0    80
2023-02-14 17:18:48.965     00:00:00.000 any     2c0f:eb98:14::5        1(33.3)    10000(33.3)   800000(33.3)        0        0    80

Summary: total flows: 3, total bytes: 2.4 M, total packets: 30000, avg bps: 236298, avg pps: 369, avg bpp: 80
```

**Comment by phaag** [comment]
This is expected behavior. The duration of the flows is 0 - perhaps, your flows are very short, or it’s an event record. You can find out more, if you look at the flow in -o raw mode. 
If the duration is 0, the pps and bps is also 0, as no per second value can be calculated. However, if you have packets and bytes, a bytes per packet value is possible.

**Comment by thezoggy** [comment]
I just thought it was odd how a flow wouldnt have the avg but the flow summary does. But your explanation makes sense, and I can confirm these are very short lived flows.

In relation, I have some other questions with this.
I wanted to look at a customer spamming us with v6 na/ra..  we can look at traffic like  `proto icmp6` but I wanted to get more info before passing along.

1) I see you can filter by icmp-code / icmp-type  but it does not seem to work for icmp6?
2) Also with the icmp-code/type you can only match on specific value not do a range using `>, <, LT, GT` ?
3) There is no way to aggregate by the type/code

**Comment by phaag** [comment]
there is no filter for icmp6, as icmp is merged in the final record. However, you can use a filter like `ipv6 and icmp-type ..` in order to filter for such type/code. But you are right, you can only match a specific value. So far the use case for a range was not on the table but can be easily implemented.
As of aggregation, you can try to use: `nfdump -r … -s dstport ipv6 and proto icmp` , which is a trick, as icmp is coded in dst port, but the filter limits to icmp6. 
Give it a try …
