### ISSUE TITLE
request: nfreplay lose exporter IP info

### ISSUE THREAD

**Issue by aalku** [phaag/nfdump#441]
Hello. I need this https://github.com/phaag/nfdump/issues/248 change but in the nfreplay command. It would be great.

It was already requested by someone else in a comment: https://github.com/phaag/nfdump/issues/248#issuecomment-745295161

Thank you! Great work! :)

**Comment by phaag** [comment]
Well - by definition, the exporter IP field is the ip of the sender. If you replay flows, you act again as a sender and therefore you get a new IP at the receiving and. The collector can not distinguish between a normal exporting device and nfreplay.

This is also different from the IP spoofing of nfcapd. It includes a packet repeater and this packet repeater re-sends the received packets to a new IP without looking into it. Therefore the two are not the same.

**Comment by aalku** [comment]
Several fields of the flows are relative to the exporter and make no sense if you don't know which router originally generated that flow. For example you have the numeric id (ifIndex) of the in and out interfaces and they are not relative to the last sender but to the router that generated the flow.

I disagree with you. The exporter is not the last sender but the router that generated the flow in the first instance. A flow is a record of what happened in that router and which router it was in is a key field to preserve and the only way to preserve that data seems to be spoofing the IP. Correct me here if you know other way, please.

Also replaying flows is a very useful tool for testing in application development scenarios but you need to simulate a number of different exporters. Without that in order to stimulate 100 exporters you would need to create 100 different loopback network interfaces or something. I would want to record real flows and replay them all the times I want.

**Comment by phaag** [comment]
Again - the collector nfcapd can not distinguish between a flow exporter such as router fw or other device and nfreplay. The exporter IP is added internally in nfcapd and is *not* a field from ipfix or netflow decoding. It marks by definition which IP sent the flows. It's a goody from nfcapd - It is the last sender, whether you disagree or not. You have to identify your exporter otherwise to make sense of the fields, if this is required such as exporter ID. 

The only solution to keep the original IP is record forwarding using the nfdump protocol ID and not v5 or v9 records. For example nfpcapd can forward pcap converted records to nfcapd. However, this requires to have another nfcapd running at the remote IP. So far nfreplay replays flows in standard v5 or v9 decoding. Using standard netflow means you could add any other collector. Using nfdump protocol ID is understood only by nfcapd. 

Using nfdump protocol ID for nfreplay is work in progress and not yet in the current code branch.

**Comment by phaag** [comment]
You may try the current master repo for an update to replay flows with nfdump protocol.
To run, use `nfreplay -v 250 ....` and make sure nfcapd is running at the other end.

**Comment by aalku** [comment]
Thank you!!

**Comment by phaag** [comment]
If it does not work, please reopen the ticket.
