### ISSUE TITLE
Default IPv6 route (::/0) does not filter interfaces.

### ISSUE THREAD

**Issue by remontti** [phaag/nfdump#474]
On these interfaces (170), I only have IPv6 traffic.
```
# nfdump -r '/var/rr-flows/Border/2023/10/06/nfcapd.202310061625' -n 5 'in if 170 AND net ::/0' -6 -A inif -O bytes 
Date first seen             Duration       Input   Packets    Bytes      bps    Bpp Flows
No matching flows

```

However, if I specify ::/1, it returns data.
```
# nfdump -r '/var/rr-flows/Border/2023/10/06/nfcapd.202310061625' -n 5 'in if 170 OR in if 153 AND net ::/1' -6 -A inif -O bytes 
Date first seen             Duration       Input   Packets    Bytes      bps    Bpp Flows
2023-10-06 16:24:55.000     00:05:51.000     170     8.6 M   11.4 G  260.4 M   1327  1442
2023-10-06 16:24:51.000     00:05:59.000     153     4.0 M    4.7 G  105.6 M   1194  1281
```

And when I don't specify an interface, it returns data from two interfaces that only have IPv4 traffic.
```
# nfdump -r '/var/rr-flows/Border/2023/10/06/nfcapd.202310061625' -n 2 'net ::/0' -6 -A inif -O bytes 
Date first seen             Duration       Input   Packets    Bytes      bps    Bpp Flows
2023-10-06 16:24:54.000     00:05:58.000     169    89.0 M  115.4 G    2.6 G   1296 22576
2023-10-06 16:24:54.000     00:05:58.000     152    49.5 M   56.8 G    1.3 G   1146 18294
```

**Comment by phaag** [comment]
The expression `::/0` is defined as default route, that's correct. However, nfdump does not know what your default route is and applies a mask that does not return any data. I should block the value `0` for the net mask in order to avoid unexpected results. 

The reason for the IPv4 traffic is the unspecific IPv6 net and the way IP addresses (v4/v6) are handled internally. This need to be fixed. Thanks!

Please note, that your command lines you show are invalid. You can not add arguments after the filter. This yields in a syntax error. Always put your filter last in the command line.

**Comment by phaag** [comment]
Fixed in master branch.
