### ISSUE TITLE
Memory leaks in OpenNewFile()

### ISSUE THREAD

**Issue by Lukas955** [phaag/nfdump#49]
Hello,

I found significant memory leaks in OpenNewFile() (/bin/nffile.c) function when it is not possible to create a new file (for example, creating the file in a directory without permission). The problem is probably caused by unfreed structure  "nffile" for the file.

Lukas

**Comment by phaag** [comment]
Under normal operation, there i no problem and no leak. The leak happens, if you have a permission problem writing files or the file system is full. In that event, it is recommended anyway to restart the services, in order to guarantee proper operation. However, the code in nffile was rearranged to prevent this leak.
