### ISSUE TITLE
when daemonizing, requesting to set uid and gid to some user AND writing PIDfile -> permission denied encountered

### ISSUE THREAD

**Issue by MrdUkk** [phaag/nfdump#499]
for example 
as root:
nfcapd -D -t 60 -u nfd -g nfd -M /var/netflows -p 2055 -P /var/run/nfcapd.pid

got
Permissions denied /var/run/nfcapd.pid

because /run is writable only by root.  For example on RHEL-based distros. thats system-wide location for that specific files.

probably by moving PID file creation function BEFORE changing gid&uid - will fix problem.

**Comment by phaag** [comment]
Ok - I see. I will check for a decent change.

**Comment by phaag** [comment]
Looking at the problem I would propose, that your startup script creates a sub directory such as `/var/run/nfcapd/` and `chown` the directory to the correct user `uid/gid` and then start nfcapd with `-p /var/run/nfcapd/nfcapd.pid`. The point is, that nfcapd will cleanup the pid file, when terminated and this will fail due to insufficient permissions of /var/run. You have a permission problem either when startup or terminate the process.
In whatever directory you write your pid file, it is expected to be able to create, write and delete a file. 
Alternatively you may write the pid file into `/run/user/nfcapd.pid` which exists in may Linuxes.

**Comment by phaag** [comment]
That sounds reasonable. I close this issue. If you need some more help, feel free to re-open.
